export const NEWS_GET_ALL = "NEWS_GET_ALL";
export const NEWS_GET_BY_ID = "NEWS_GET_BY_ID";
export const NEWS_GET_NEXT = "NEWS_GET_NEXT";

export const UIACTIVITY_IS_LOADING = "UIACTIVITY_IS_LOADING";
